name: ci
on:
  push:
    branches: [v2]
  pull_request:
    branches: [v2]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9.4.0

      - name: Install node-gyp prerequisites
        run: sudo apt update && sudo apt install -y build-essential python3 pkg-config libudev-dev libusb-1.0-0-dev

      - uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run lint and fix
        run: pnpm run lint:fix

      - name: Build packages
        run: pnpm run build
